@url = http://localhost:5008

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTU3NjkzYi00YTcxLTQ4MDQtOTFlYS0wY2RmZDkxYjc2MjciLCJ1bmlxdWVfbmFtZSI6IjJlNTc2OTNiLTRhNzEtNDgwNC05MWVhLTBjZGZkOTFiNzYyNyIsImp0aSI6ImZjNzhlMDAxLTMyNmEtNDEzZC05NTIyLWU5ZjAwZDhmMDJlYyIsImlhdCI6IjE3MzY5Nzc5NDc3NzEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicG9saWNpZXMiOlsiaXRlbXMiLCJpbnZlbnRvcnkiXSwibmJmIjoxNzM2OTc3OTQ3LCJleHAiOjE3NDU1MzE1NDcsImlzcyI6IlBsYXkuVXNlci5TZXJ2aWNlIn0.P8ow1IH51kmM7HBk7GiO1cHlakWntYXg9Eseg3Ki0jM

@itemId = 1095dd7b-ffe6-4cd7-aaba-8273bc0dcc53
@userId = 52e9848b-bb0c-4d85-8d67-b32768d6de8e

###
GET {{url}}/publishCreateItem

### PLAY-USER ###
###
POST {{url}}/play-user/signUp
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@play.com",
  "password": "secret",
  "role": "user",
  "claims": {
    "policies": [
      "items",
      "inventory"
    ]
  }
}

###
POST {{url}}/play-user/signIn
Content-Type: application/json

{
    "email": "user1@play.com",
    "password": "secret"
}

###
GET {{url}}/play-user
Authorization: Bearer {{accessToken}}

### PLAY-ITEMS ###
### HomePage
GET {{url}}/play-items

### Get Items
GET {{url}}/play-items/items

### Get
GET {{url}}/play-items/items/{{itemId}}

### Delete All Items sync
DELETE {{url}}/play-items/items

### Delete All Items async
DELETE {{url}}/play-items/items/delete

### Create
POST {{url}}/play-items/items
Content-Type: application/json

{
  "name": "XXXXXL Potion",
  "description": "Easy damage",
  "price": 66.99
}

### Update
PUT {{url}}/play-items/items/{{itemId}}
Content-Type: application/json

{
  "name": "Scr",
  "description": "Easy spells",
  "price": 35.99
}

### Delete
DELETE {{url}}/play-items/items/{{itemId}}

### PLAY-INVENTORY ###
### Browse Inventory+
GET {{url}}/play-inventory

GET {{url}}/play-inventory/inventory
Authorization: Bearer {{accessToken}}

### Browse Catalog Items
GET {{url}}/play-inventory/items

### Purchase Item
POST {{url}}/play-inventory/items/{{itemId}}/purchase
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "quantity": 1
}

###
POST http://localhost:5010/trigger/52e9848b-bb0c-4d85-8d67-b32768d6de8e?status=pending

###
POST http://localhost:5010/trigger/52e9848b-bb0c-4d85-8d67-b32768d6de8e?status=completed

###
POST http://localhost:5010/trigger/52e9848b-bb0c-4d85-8d67-b32768d6de8e?status=rejected