@url = http://localhost:5008

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyODI2MzMyMi03NGUwLTQ3MzUtYWQ5Ni00ZjY4ODUxYTgxMGUiLCJ1bmlxdWVfbmFtZSI6IjI4MjYzMzIyLTc0ZTAtNDczNS1hZDk2LTRmNjg4NTFhODEwZSIsImp0aSI6IjZlZjM4ZmMyLTQ2MzItNDdhOS1hZGNhLTE1MWY3Yzc3YTVmZSIsImlhdCI6IjE3NDA0Mzg2NjIxMzkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicG9saWNpZXMiOlsiaXRlbXMiLCJpbnZlbnRvcnkiXSwibmJmIjoxNzQwNDM4NjYyLCJleHAiOjE3NDg5OTIyNjIsImlzcyI6IlBsYXkuVXNlci5TZXJ2aWNlIn0.JvQSz3yjELyWd-I3ct6hHnZSQhWA2ZN3_4H2egvAqd4

@itemId = a51bd6ca-6ca9-48e7-90c4-e75f290f7a9a
@crafterId = b69f5ef7-bf93-4de2-a62f-064652d8dd19
@userId = 28263322-74e0-4735-ad96-4f68851a810e

###
GET {{url}}/publishCreateItem

### PLAY-USER ###
###
POST {{url}}/play-user/signUp
Content-Type: application/json

{
  "username": "user2",
  "email": "user2@play.com",
  "password": "secret",
  "role": "user",
  "claims": {
    "policies": [
      "items",
      "inventory"
    ]
  }
}

###
POST {{url}}/play-user/signIn
Content-Type: application/json

{
    "email": "user2@play.com",
    "password": "secret"
}

###
GET {{url}}/play-user
Authorization: Bearer {{accessToken}}

###
GET {{url}}/play-user/{{userId}}

### PLAY-ITEMS ###
### HomePage
GET {{url}}/play-items

### Get Items
GET {{url}}/play-items/items

### Get
GET {{url}}/play-items/items/{{itemId}}

### Delete All Items sync
DELETE {{url}}/play-items/items

### Delete All Items async
DELETE {{url}}/play-items/items/delete

### Create
POST {{url}}/play-items/items
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "XXXXXL Potion",
  "description": "Easy damage",
  "price": 66.99,
  "crafterId": "{{crafterId}}",
  "element": "Fire"
}

### Update
PUT {{url}}/play-items/items/{{itemId}}
Content-Type: application/json

{
  "name": "Scr",
  "description": "Easy spells",
  "price": 35.99
}

### Delete
DELETE {{url}}/play-items/items/be39f46e-62ec-4e12-8720-b83920c3a719

### PLAY-INVENTORY ###
### Browse Inventory+
GET {{url}}/play-inventory

GET {{url}}/play-inventory/inventory
Authorization: Bearer {{accessToken}}

### Browse Catalog Items
GET {{url}}/play-inventory/items

### Purchase Item
POST {{url}}/play-inventory/items/{{itemId}}/purchase
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "quantity": 1
}

###
POST http://localhost:5010/trigger/52e9848b-bb0c-4d85-8d67-b32768d6de8e?status=pending

###
POST http://localhost:5010/trigger/52e9848b-bb0c-4d85-8d67-b32768d6de8e?status=completed

###
POST http://localhost:5010/trigger/52e9848b-bb0c-4d85-8d67-b32768d6de8e?status=rejected