@url = http://localhost:5008

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTU3NjkzYi00YTcxLTQ4MDQtOTFlYS0wY2RmZDkxYjc2MjciLCJ1bmlxdWVfbmFtZSI6IjJlNTc2OTNiLTRhNzEtNDgwNC05MWVhLTBjZGZkOTFiNzYyNyIsImp0aSI6ImZjNzhlMDAxLTMyNmEtNDEzZC05NTIyLWU5ZjAwZDhmMDJlYyIsImlhdCI6IjE3MzY5Nzc5NDc3NzEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicG9saWNpZXMiOlsiaXRlbXMiLCJpbnZlbnRvcnkiXSwibmJmIjoxNzM2OTc3OTQ3LCJleHAiOjE3NDU1MzE1NDcsImlzcyI6IlBsYXkuVXNlci5TZXJ2aWNlIn0.P8ow1IH51kmM7HBk7GiO1cHlakWntYXg9Eseg3Ki0jM

@itemId = c5ab196a-bca1-4eb8-ae10-a367ca655837
@userId = 52e9848b-bb0c-4d85-8d67-b32768d6de8e
@creafterId = d83935da-7678-4161-994c-586962868980

### PLAY-USER ###
###
POST {{url}}/play-user/signUp
Content-Type: application/json

{
  "username": "user8",
  "email": "user8@play.com",
  "password": "secret",
  "role": "user",
  "claims": {
    "policies": [
      "items",
      "inventory"
    ]
  }
}

###
POST {{url}}/play-user/signIn
Content-Type: application/json

{
    "email": "user1@play.com",
    "password": "secret"
}

###
GET {{url}}/play-user
Authorization: Bearer {{accessToken}}

### PLAY-ITEMS ###
### Hello
GET {{url}}/play-items

### Get Items
GET {{url}}/play-items/items

### Get
GET {{url}}/play-items/items/{{itemId}}

### Get by Crafter
GET {{url}}/play-items/crafters/{{creafterId}}

### Delete All Items sync
DELETE {{url}}/items

### Delete All Items async
DELETE {{url}}/items/delete

### Create
POST {{url}}/play-items/items
Content-Type: application/json

{
  "name": "Trident",
  "description": "Wave is coming",
  "price": 15.15,
  "crafterId": "{{creafterId}}",
  "element": "Water"
}

### Create with Crafter
POST {{url}}/play-items/items/crafter
Content-Type: application/json

{
  "name": "Sword",
  "description": "Easy damage",
  "price": 27.52,
  "crafterName": "DinFoon"
}

### Update
PUT {{url}}/play-items/items/{{itemId}}
Content-Type: application/json

{
  "name": "Tridentum",
  "description": "Poseidons strenght",
  "price": 30
}

### Delete
DELETE {{url}}/play-items/items/{{itemId}}

### CRAFTERS
POST {{url}}/play-items/crafters
Content-Type: application/json

{
  "name": "DinFoon"
}

###
GET {{url}}/crafters/{{creafterId}}

### PLAY-INVENTORY ###
### Browse Inventory
GET {{url}}/play-inventory/inventory
Authorization: Bearer {{accessToken}}

### Browse Catalog Items
GET {{url}}/play-inventory/items

### Purchase Item
POST {{url}}/play-inventory/items/{{itemId}}/purchase
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "quantity": 1
}

###
POST http://localhost:5010/trigger/52e9848b-bb0c-4d85-8d67-b32768d6de8e?status=pending

###
POST http://localhost:5010/trigger/52e9848b-bb0c-4d85-8d67-b32768d6de8e?status=completed

###
POST http://localhost:5010/trigger/52e9848b-bb0c-4d85-8d67-b32768d6de8e?status=rejected