@url = http://localhost:5002

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTU3NjkzYi00YTcxLTQ4MDQtOTFlYS0wY2RmZDkxYjc2MjciLCJ1bmlxdWVfbmFtZSI6IjJlNTc2OTNiLTRhNzEtNDgwNC05MWVhLTBjZGZkOTFiNzYyNyIsImp0aSI6ImZjNzhlMDAxLTMyNmEtNDEzZC05NTIyLWU5ZjAwZDhmMDJlYyIsImlhdCI6IjE3MzY5Nzc5NDc3NzEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicG9saWNpZXMiOlsiaXRlbXMiLCJpbnZlbnRvcnkiXSwibmJmIjoxNzM2OTc3OTQ3LCJleHAiOjE3NDU1MzE1NDcsImlzcyI6IlBsYXkuVXNlci5TZXJ2aWNlIn0.P8ow1IH51kmM7HBk7GiO1cHlakWntYXg9Eseg3Ki0jM

@itemId = 54a811b2-ba74-409b-9cb8-b01a026b27a2
@userId = 52e9848b-bb0c-4d85-8d67-b32768d6de8e


### PLAY-USER ###
###
POST {{url}}/play-user/signUp
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@play.com",
  "password": "secret",
  "role": "user",
  "claims": {
    "policies": [
      "items",
      "inventory"
    ]
  }
}

###
POST {{url}}/play-user/signIn
Content-Type: application/json

{
    "email": "user1@play.com",
    "password": "secret"
}

###
GET {{url}}/play-user
Authorization: Bearer {{accessToken}}

### PLAY-ITEMS ###
### Get Items
GET {{url}}/items

### Get Items
GET {{url}}

### Get
GET {{url}}/items/{{itemId}}

### Delete All Items sync
DELETE {{url}}/items

### Delete All Items async
DELETE {{url}}/items/delete

### Create
POST {{url}}/items
Content-Type: application/json

{
  "name": "Sword",
  "description": "Easy damage",
  "price": 27.52
}

### Create with Crafter
POST {{url}}/items/crafter
Content-Type: application/json

{
  "name": "Sword",
  "description": "Easy damage",
  "price": 27.52,
  "crafterName": "DinFoon"
}

### Update
PUT {{url}}/items/{{itemId}}
Content-Type: application/json

{
  "name": "Antidoteeeeeee",
  "description": "Cures poison",
  "price": 30
}

### Delete
DELETE {{url}}/items/{{itemId}}

### PLAY-INVENTORY ###
### Browse Inventory
GET {{url}}/play-inventory/inventory
Authorization: Bearer {{accessToken}}

### Browse Catalog Items
GET {{url}}/play-inventory/items

### Purchase Item
POST {{url}}/play-inventory/items/{{itemId}}/purchase
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "quantity": 1
}

###
POST http://localhost:5010/trigger/52e9848b-bb0c-4d85-8d67-b32768d6de8e?status=pending

###
POST http://localhost:5010/trigger/52e9848b-bb0c-4d85-8d67-b32768d6de8e?status=completed

###
POST http://localhost:5010/trigger/52e9848b-bb0c-4d85-8d67-b32768d6de8e?status=rejected