// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Play.World.Infrastructure.Postgres;

#nullable disable

namespace Play.World.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(WorldPostgresDbContext))]
    [Migration("20260108234013_FixTypoInPosition")]
    partial class FixTypoInPosition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("play.world")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Play.World.Domain.Entities.ItemLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DroppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCollected")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Point>("Position")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("Position");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "gist");

                    b.ToTable("ItemLocations", "play.world");
                });

            modelBuilder.Entity("Play.World.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Polygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon, 4326)")
                        .HasColumnName("Boundary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.ToTable("Zones", "play.world");
                });

            modelBuilder.Entity("Play.World.Domain.Entities.Zone", b =>
                {
                    b.OwnsOne("Play.World.Domain.ValueObjects.ZoneType", "Type", b1 =>
                        {
                            b1.Property<Guid>("ZoneId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Type");

                            b1.HasKey("ZoneId");

                            b1.ToTable("Zones", "play.world");

                            b1.WithOwner()
                                .HasForeignKey("ZoneId");
                        });

                    b.Navigation("Type")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
